language: python
dist: xenial
services:
    - xvfb


cache:
  directories:
    #- $HOME/.cache/pip
    #- $HOME/miniconda3
    - $HOME/.config/sequana

matrix:
  include:
    - python: 3.6
    - python: 3.7.3


before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda config --add channels defaults
    - conda config --add channels conda-forge

install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv

  #- conda install --yes --file requirements.txt
  # to install specific version of multiqc, we install packages manually
  - conda install --yes singularity

  - python setup.py install

# # command to run tests, e.g. python setup.py test
script: 
  - pytest -v --cov-config=.coveragerc_travis --durations=10  test/ --cov=damona --cov-report term-missing --timeout 300 

after_success:
  coveralls
