language: python
dist: xenial
services:
    - xvfb


cache:
  directories:
    #- $HOME/.cache/pip
    #- $HOME/miniconda3
    - $HOME/.config/sequana

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8


before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    - conda config --add channels r
    - conda config --add channels bioconda
    - conda config --add channels defaults
    - conda config --add channels conda-forge

install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda create --yes --name testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install pytest pytest-cov pytest-timeout pytest-xdist pytest-mock pytest-runner
  - conda install --yes singularity
  - pip install coverage coveralls mock pytest-mock
  # aug 2020 python setup does not seem to install dependencues
  - pip install -r requirements.txt
  - python setup.py install

# # command to run tests, e.g. python setup.py test
script: 
  - pytest -v  --durations=10  test/ --cov=damona --cov-report term-missing --timeout 300 

after_success:
  coveralls
