name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore: []

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master
    - name: Test docker
      run: |
          set -x
          docker version
          docker run --rm hello-world
    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: conda
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies conda
      run: |
        conda install -c conda-forge mamba --quiet
        mamba install -c conda-forge singularity --quiet
    - name: Install Damona using pip
      run: | 
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest --cov-report term --cov=damona 
      env:
        DAMONA_EXE: /usr/share/miniconda/bin/damona
        DAMONA_PATH: /home/runner/.config/damona
    - name: coveralls
      run: |
        coveralls --service=github
